# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql
  pool: 5
  timeout: 5000

development:
  adapter: mysql
  database: demo
  host: localhost
  username: root
  password: root

test:
  adapter: mysql
  database: demo
  host: localhost
  username: root
  password: root

production:
  adapter: mysql
  database: demo
  host: localhost
  username: root
  password: root